CREATE TABLE WorkflowDefinition(
ID VARCHAR(26) NOT NULL Primary Key,
Name NVARCHAR(50) NULL,
[Enabled] BIT NULL,
Remark VARCHAR(500) NULL,
Creator VARCHAR(50) NULL,
CreateTime DATETIME NULL
);

CREATE TABLE ActivityDefinition(
ID VARCHAR(26) NOT NULL PRIMARY KEY,
WorkflowDefinitionID VARCHAR(26) NULL,
[Page] VARCHAR(200) NULL,
Name NVARCHAR(50) NULL,
[Enabled] BIT NULL,
[Type] INT NULL,
Creator VARCHAR(50) NULL,
CreateTime DATETIME NULL,
Remark NVARCHAR(500) NULL
);

CREATE TABLE LinkDefinition(
ID VARCHAR(26) NOT NULL PRIMARY KEY,
FromActivityDefinitionID VARCHAR(26) NULL,
ToActivityDefinitionID VARCHAR(26) NULL,
Name NVARCHAR(50) NULL,
Creator VARCHAR(50) NULL,
CreateTime DATETIME NULL,
Remark NVARCHAR(500) NULL
);

CREATE TABLE Workflow(
ID VARCHAR(26) NOT NULL PRIMARY KEY,
WorkflowDefinitionID VARCHAR(26) NULL,
Name NVARCHAR(50) NULL,
Creator VARCHAR(50) NULL,
CreateTime DATETIME NULL,
[Status] INT NULL
);

CREATE TABLE Activity(
ID VARCHAR(26) NOT NULL PRIMARY KEY,
ActivityDefinitionID VARCHAR(26) NULL,
Name NVARCHAR(50) NULL,
[Page] VARCHAR(200) NULL,
Creator VARCHAR(50) NULL,
CreateTime DATETIME NULL,
[Type] VARCHAR(10) NULL,
WorkflowID VARCHAR(26) NULL,
[Status] INT NULL,
ReadTime DATETIME NULL,
ProcessTime DATETIME NULL
);

CREATE TABLE Link(
ID VARCHAR(26) NOT NULL PRIMARY KEY,
LinkDefinitionID VARCHAR(26) NULL,
FromActivityID VARCHAR(26) NULL,
ToAcivityID VARCHAR(26) NULL,
Name NVARCHAR(50) NULL,
Creator VARCHAR(50) NULL,
CreateTime DATETIME NULL,
Passed BIT NULL,
PassedTime DATETIME NULL
);

CREATE TABLE Approval(
ID VARCHAR(26) NOT NULL PRIMARY KEY,
ActivityID VARCHAR(26) NULL,
[Status] INT NULL,
Remark NVARCHAR(500) NULL,
Creator VARCHAR(50) NULL,
CreateTime DATETIME NULL
);

CREATE TABLE Context(
ID VARCHAR(26) NOT NULL PRIMARY KEY,
WorkflowID VARCHAR(26) NULL
);

CREATE TABLE Parameter(
ID VARCHAR(26) NOT NULL PRIMARY KEY,
ContextID VARCHAR(26) NULL,
[Key] VARCHAR(50) NULL,
[Value] NVARCHAR(4000) NULL
);

CREATE TABLE ActivityAuthDefinition(
ID VARCHAR(26) NOT NULL PRIMARY KEY,
[Type] INT NULL,
[Value] VARCHAR(26) NULL,
ActivityID VARCHAR(26) NULL
);

CREATE TABLE ActivityAuth(
ID VARCHAR(26) NOT NULL PRIMARY KEY,
AcitivityAuthDefinitionID VARCHAR(26) NULL,
[Type] INT NULL,
[Value] VARCHAR(26) NULL,
AcitivityID VARCHAR(26) NULL
);

CREATE TABLE Task(
ID VARCHAR(26) NOT NULL PRIMARY KEY,
AcitivityID VARCHAR(26) NULL,
Name NVARCHAR(50) NULL,
Creator VARCHAR(50) NULL,
CreateTime DATETIME NULL,
Remark NVARCHAR(500) NULL,
[Status] INT NULL,
ReadTime DATETIME NULL,
ProcessTime DATETIME NULL
);